/**
 * @description       : This helper class communicates with the Linkedin AP NC Setting Metadata
 * @author            : Amit Kumar [amitniitmca@gmail.com]
 * @last modified on  : 15-02-2022
 * @last modified by  : Amit Kumar [amitniitmca@gmail.com]
 **/
public inherited sharing class LinkedinApNcSettingHelper{
    private static final String NAMESPACE = 'liman__';
    private static final String OBJECT_NAME = 'Linkedin_AP_NC_Setting__mdt';
    private static final List<String> FIELDS = new List<String>{ NAMESPACE + 'AP_Created__c', NAMESPACE + 'AP_Name__c', NAMESPACE + 'Client_Id__c', NAMESPACE + 'Client_Secret__c', NAMESPACE + 'Marketing_Developer_Product__c', NAMESPACE + 'NC_Authenticated__c', NAMESPACE + 'NC_Created__c', NAMESPACE + 'NC_Name__c', NAMESPACE + 'Share_On_Product__c', NAMESPACE + 'Sign_In_Product__c', NAMESPACE + 'User_Id__c'};

    // public void createRecord(String developerName, )
}